# Generated by Django 5.2.4 on 2025-07-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('photoName', models.URLField()),
                ('soldOut', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pizzas',
                'ordering': ['name'],
            },
        ),
    ]
